---
- hosts: localhost
  
  tasks:
    - name: Login de acesso usando segredo com VAULT
      include_vars:
        file: /etc/ansible/segredo.yml
        name: secret

    - name: vCenter Login
      uri:
        url: "https://{{secret.vcenter}}/rest/com/vmware/cis/session"
        force_basic_auth: yes
        method: POST
        user: "{{secret.username}}"
        password: "{{secret.password}}"
        status_code: 200
        validate_certs: no
      register: login